const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db');

const Client = sequelize.define(
  'Client',
  {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4,
    },
    name: { type: DataTypes.STRING, allowNull: false },
    displayName: DataTypes.STRING,
    packageType: { type: DataTypes.STRING, defaultValue: 'starter' },
    isActive: { type: DataTypes.BOOLEAN, defaultValue: true },
    contactPerson: DataTypes.STRING,
    phone: DataTypes.STRING,
    email: DataTypes.STRING,
    openJobs: DataTypes.INTEGER,
    jobsUsed: { type: DataTypes.INTEGER, defaultValue: 0 },
    jobsTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    coordinatorsUsed: { type: DataTypes.INTEGER, defaultValue: 0 },
    coordinatorsTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    usersUsed: { type: DataTypes.INTEGER, defaultValue: 0 },
    usersTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    cvQuotaTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    tagsQuotaTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    tagsQuotaUsed: { type: DataTypes.INTEGER, defaultValue: 0 },
    contactsQuotaTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    emailsQuotaUsed: { type: DataTypes.INTEGER, defaultValue: 0 },
    emailsQuotaTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    smsBackup: { type: DataTypes.INTEGER, defaultValue: 0 },
    smsMonthly: { type: DataTypes.INTEGER, defaultValue: 0 },
    smsUsed: { type: DataTypes.INTEGER, defaultValue: 0 },
    smsTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    questionnaireBackup: { type: DataTypes.INTEGER, defaultValue: 0 },
    questionnaireMonthly: { type: DataTypes.INTEGER, defaultValue: 0 },
    emailBackup: { type: DataTypes.INTEGER, defaultValue: 0 },
    emailMonthly: { type: DataTypes.INTEGER, defaultValue: 0 },
    hiroAiMonthly: { type: DataTypes.INTEGER, defaultValue: 0 },
    storageQuotaUsed: { type: DataTypes.INTEGER, defaultValue: 0 },
    storageQuotaTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    aiCreditsQuotaUsed: { type: DataTypes.INTEGER, defaultValue: 0 },
    aiCreditsQuotaTotal: { type: DataTypes.INTEGER, defaultValue: 0 },
    status: {
      type: DataTypes.ENUM('פעיל', 'לא פעיל', 'בהקפאה'),
      defaultValue: 'פעיל',
    },
    accountManager: DataTypes.STRING,
    city: DataTypes.STRING,
    region: DataTypes.STRING,
    industry: DataTypes.STRING,
    field: DataTypes.STRING,
    contactIsActive: { type: DataTypes.BOOLEAN, defaultValue: true },
    creationDate: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    recruitingCoordinator: DataTypes.STRING,
    creationDate: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    renewalDate: { type: DataTypes.DATE },
    mainContactName: DataTypes.STRING,
    mainContactEmail: DataTypes.STRING,
    mainContactPhone: DataTypes.STRING,
    smsSource: DataTypes.STRING,
    authorizedIps: DataTypes.STRING,
    primaryColor: DataTypes.STRING,
    logoUrl: DataTypes.STRING,
    modules: { type: DataTypes.JSONB, defaultValue: {} },
    users: { type: DataTypes.JSONB, defaultValue: [] },
    metadata: { type: DataTypes.JSONB, defaultValue: {} },
    events: { type: DataTypes.JSONB, defaultValue: [] },
    documents: { type: DataTypes.JSONB, defaultValue: [] },
    finance: { type: DataTypes.JSONB, defaultValue: {} },
  },
  {
    tableName: 'clients',
  },
);

module.exports = Client;

