const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src/services/chatService.js');
const data = fs.readFileSync(filePath, 'utf8');
const start = data.indexOf('const SYSTEM_TEMPLATE_CANDIDATE_PROFILE');
const end = data.indexOf('const tryParseJson');
if (start === -1 || end === -1) {
  throw new Error('markers not found');
}
const lines = [
  "const SYSTEM_TEMPLATE_CANDIDATE_PROFILE = ({ contextData, overridePrompt }) => {",
  "  const pruned = pruneContextData(contextData);",
  "  const cvText = (contextData && typeof contextData.searchText === 'string') ? contextData.searchText.slice(0, 20000) : '';",
  "  const schemaDescription = `",
  "Candidate schema fields (preferred updates):",
  "- fullName, title, professionalSummary, location, availability",
  "- education, workExperience, tags, softSkills, techSkills",
  "- candidateNotes, desiredRoles, salaryMin, salaryMax",
  "- phone, email",
  "Use these fields to match against whatever the user just wrote; respond with JSON edits for the ones that change.",
  "`;",
  "  const candidateSchemaText = `",
  "Candidate schema (from backend/src/models/Candidate.js):",
  "${[",
  "    'fullName (STRING, not null)',",
  "    'status (STRING)',",
  "    'phone (STRING)',",
  "    'email (STRING)',",
  "    'address (STRING)',",
  "    'idNumber, maritalStatus, gender, drivingLicense, mobility (STRING)',",
  "    'userId (UUID, nullable)',",
  "    'employmentType, jobScope, availability, physicalWork (STRING)',",
  "    'birthYear, birthMonth, birthDay, age (STRING)',",
  "    'title (STRING), professionalSummary (TEXT)',",
  "    'profilePicture, resumeUrl (STRING)',",
  "    'tags, internalTags (ARRAY of STRING)',",
  "    'skills (JSONB { soft: [], technical: [] })',",
  "    'languages (JSONB array)',",
  "    'salaryMin, salaryMax (INTEGER)',",
  "    'workExperience (JSONB array)',",
  "    'industryAnalysis (JSONB)',",
  "    'education (JSONB array)',",
  "    'internalNotes, candidateNotes (TEXT)',",
  "    'source (STRING)',",
  "    'jobScopes, highlights (ARRAY of STRING)',",
  "    'experience (JSONB array)',",
  "    'lastActivity, lastActive (STRING)',",
  "    'matchScore (INTEGER)',",
  "    'matchAnalysis (JSONB)',",
  "    'sector, companySize, field, industry (STRING)',",
  "    'embedding (JSONB nullable), searchText (TEXT)',",
  "    'isArchived (BOOLEAN)',",
  "].join('\\n')}",
  "Use this schema to find matches between the user's query and fields worth updating.",
  "`;",
  "  const groundingRules = `",
  "You are Hiro, an expert AI Career Coach and Recruitment Assistant.",
  "Grounding (CRITICAL):",
  "- You MUST base suggestions ONLY on the provided candidate profile JSON and the provided CV text.",
  "- Do NOT invent new professions/tech stacks/experience that are not supported by the CV text.",
  "- If you cannot support a suggestion from the CV text/profile, DO NOT suggest it.",
  "- When suggesting skills/roles/tags, prefer items that explicitly appear in the CV text.",
  "Output formatting:",
  "- Follow the user's requested JSON schema STRICTLY.",
  "- Return ONLY valid JSON, no markdown, no extra text.",
  "${schemaDescription}",
  "${candidateSchemaText}",
  "`;",
  "",
  "  const contextBlock = `",
  "Candidate profile JSON (ground truth):",
  "${JSON.stringify(pruned || {}, null, 2)}",
  "",
  "CV text (ground truth, may be partial):",
  "${cvText || ''}",
  "`;",
  "",
  "  return `${groundingRules}\n${overridePrompt ? String(overridePrompt) : ''}\n${contextBlock}`;",
  "};",
];
const newFunc = lines.join('\n');
const updated = data.slice(0, start) + newFunc + data.slice(end);
fs.writeFileSync(filePath, updated, 'utf8');
