ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS "distributionEmail" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "distributionSms" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "distributionWhatsapp" BOOLEAN NOT NULL DEFAULT true;
