/**
 * Machine-readable capability catalog for the Hiro agent API.
 * Mirrors the internal Notion matrix agents use for planning.
 */
const AGENT_CAPABILITIES = [
  {
    id: 'clients.contacts.update',
    title: 'עריכת איש קשר קיים',
    domain: 'לקוחות ואנשי קשר',
    status: 'available',
    description: 'עדכון פרטים של איש קשר קיים (טלפון, תפקיד, מייל, הגדרות דיוור).',
    note: null,
    endpoint: 'PATCH /api/agent/clients/:clientId/contacts/:contactId',
    scope: 'agent:clients:write',
  },
  {
    id: 'clients.contacts.create',
    title: 'יצירת איש קשר',
    domain: 'לקוחות ואנשי קשר',
    status: 'available',
    description: 'יצירת איש קשר חדש תחת לקוח וארגון מקושר.',
    note: null,
    endpoint: 'POST /api/agent/clients/:clientId/contacts',
    scope: 'agent:clients:write',
  },
  {
    id: 'clients.contacts.delete',
    title: 'מחיקת איש קשר',
    domain: 'לקוחות ואנשי קשר',
    status: 'available',
    description: 'מחיקת איש קשר קיים.',
    note: null,
    endpoint: 'DELETE /api/agent/clients/:clientId/contacts/:contactId',
    scope: 'agent:clients:write',
  },
  {
    id: 'clients.organization_link',
    title: 'קישור ארגון ללקוח',
    domain: 'לקוחות ואנשי קשר',
    status: 'available',
    description: 'קישור ארגון קיים מהקטלוג ללקוח (כמו כפתור "קשר לארגון").',
    note: 'קריאה בודדת לכל ארגון, אין batch.',
    endpoint: 'POST /api/agent/clients/:clientId/organization-link',
    scope: 'agent:clients:write',
  },
  {
    id: 'clients.update_or_create',
    title: 'עדכון פרטי לקוח / יצירת לקוח חדש',
    domain: 'לקוחות ואנשי קשר',
    status: 'unavailable',
    description: 'אין אפשרות לערוך פרטי לקוח עצמו או לפתוח לקוח חדש — רק לקשר חברה ולנהל אנשי קשר.',
    note: null,
    endpoint: null,
    scope: null,
  },
  {
    id: 'system.candidates_jobs_users',
    title: 'גישה למועמדים, משרות ומשתמשים',
    domain: 'מערכת וכניסה',
    status: 'unavailable',
    description: 'הסוכן חסום מכל נתוני המועמדים, המשרות והמשתמשים — בכוונה (אבטחה).',
    note: null,
    endpoint: null,
    scope: null,
  },
  {
    id: 'tags.synonyms.edit_in_place',
    title: 'עריכת סינון קיים (שינוי טקסט / עדיפות)',
    domain: 'קטלוג תגיות',
    status: 'unavailable',
    description: 'אין אפשרות לערוך סינון קיים במקום.',
    note: 'עוקף: למחוק ולהוסיף מחדש (המזהה ישתנה). השתמשו ב-PATCH /api/agent/tags/:id/execute עם remove_synonyms ואז add_synonyms.',
    endpoint: 'PATCH /api/agent/tags/:id/execute',
    scope: 'agent:tags:write',
  },
  {
    id: 'tags.protected_catalog',
    title: 'תגיות מוגנות בקטלוג',
    domain: 'קטלוג תגיות',
    status: 'available',
    description:
      'תגיות עם isProtected חסומות למחיקה, מיזוג כמקור, שינוי סטטוס והעשרה עמוקה. מותר: add_synonyms / מיזוג אליהן כיעד.',
    note: 'שגיאת API: code TAG_PROTECTED — לדלג, לא לנסות שוב.',
    endpoint: 'POST /api/agent/tags/merge, PATCH /api/agent/tags/:id/execute',
    scope: 'agent:tags:write',
  },
  {
    id: 'tags.deep_enrich',
    title: 'העשרה עמוקה לתגית',
    domain: 'קטלוג תגיות',
    status: 'available',
    description: 'הרצת העשרה AI על תגית בודדת עם הקשר מלא (כמו כפתור "העשרה עמוקה" בממשק).',
    note: 'מחזיר before/after ל-tagKey, category, synonyms. עלול לשנות tagKey/category.',
    endpoint: 'POST /api/agent/tags/:id/enrich',
    scope: 'agent:tags:write',
  },
  {
    id: 'tags.update_status',
    title: 'עדכון סטטוס ואיכות תגית',
    domain: 'קטלוג תגיות',
    status: 'available',
    description: 'שינוי status (active/draft) ו/או qualityState (verified/needs_review).',
    note: null,
    endpoint: 'PATCH /api/agent/tags/:id/execute',
    scope: 'agent:tags:write',
  },
  {
    id: 'organizations.read',
    title: 'קריאת חברות חיות',
    domain: 'קטלוג חברות',
    status: 'available',
    description: 'רשימה ופרטי Organization מהקטלוג, כולל סינון לפי ח.פ, סטטוס פעילות ואיכות נתונים.',
    note: null,
    endpoint: 'GET /api/agent/organizations',
    scope: 'agent:organizations:read',
  },
  {
    id: 'organizations.duplicates',
    title: 'איתור כפילויות חברות',
    domain: 'קטלוג חברות',
    status: 'available',
    description: 'קבוצות חברות עם אותו ח.פ או אותו שם מנורמל.',
    note: null,
    endpoint: 'GET /api/agent/organizations/duplicates',
    scope: 'agent:organizations:read',
  },
  {
    id: 'organizations.update_fields',
    title: 'עדכון שדות חברה חיה',
    domain: 'קטלוג חברות',
    status: 'available',
    description: 'עדכון חלקי של כל שדות פרופיל החברה (שם, ח.פ, כתובת, סטטוס וכו\'). null מוחק ערך.',
    note: 'נעילה אופטימistית via expectedUpdatedAt. dataConfidence מוגבל לסוכן.',
    endpoint: 'PATCH /api/agent/organizations/:id/execute',
    scope: 'agent:organizations:write',
  },
  {
    id: 'organizations.create',
    title: 'יצירת חברה חדשה',
    domain: 'קטלוג חברות',
    status: 'available',
    description: 'יצירת Organization חדשה ישירות (למשל פיצול מרשומת גנרי).',
    note: '409 + existingOrganization על כפילות ח.פ/שם.',
    endpoint: 'POST /api/agent/organizations',
    scope: 'agent:organizations:write',
  },
  {
    id: 'organizations.aliases',
    title: 'ניהול כינויים לחברה',
    domain: 'קטלוג חברות',
    status: 'available',
    description: 'הוספה והסרה של aliases לחברה קיימת.',
    note: null,
    endpoint: 'PATCH /api/agent/organizations/:id/execute',
    scope: 'agent:organizations:write',
  },
  {
    id: 'organizations.additional_locations',
    title: 'כתובות נוספות לחברה',
    domain: 'קטלוג חברות',
    status: 'available',
    description: 'הוספה, עריכה והסרה של כתובות נוספות (סניף/מרלוג).',
    note: 'operations: add_additional_location, update_additional_location, remove_additional_location',
    endpoint: 'PATCH /api/agent/organizations/:id/execute',
    scope: 'agent:organizations:write',
  },
  {
    id: 'organizations.enrich',
    title: 'העשרת חברה (AI)',
    domain: 'קטלוג חברות',
    status: 'available',
    description: 'הרצת העשרה AI על חברה קיימת.',
    note: null,
    endpoint: 'POST /api/agent/organizations/:id/enrich',
    scope: 'agent:organizations:write',
  },
  {
    id: 'organizations.merge',
    title: 'מיזוג חברות',
    domain: 'קטלוג חברות',
    status: 'available',
    description: 'מיזוג חברת מקור ליעד.',
    note: null,
    endpoint: 'POST /api/agent/organizations/merge',
    scope: 'agent:organizations:write',
  },
  {
    id: 'org_ai_decisions.read',
    title: 'קריאת החלטות AI לחברות',
    domain: 'החלטות AI — חברות',
    status: 'available',
    description: 'תור החלטות create/merge/map_generic. כולל organizationId של החברה החיה.',
    note: null,
    endpoint: 'GET /api/agent/organization-ai-decisions',
    scope: 'agent:organization-ai-decisions:read',
  },
  {
    id: 'org_ai_decisions.resolve',
    title: 'סגירת החלטת AI (resolve/approve)',
    domain: 'החלטות AI — חברות',
    status: 'available',
    description: 'resolve עם reviewStatus=approved סוגר create_company בלי ליצור כפילות. approve מעדכן manualApprovalStatus בלבד.',
    note: 'create_company: החברה כבר נוצרה בצינור — resolve רק מקשר organizationId.',
    endpoint: 'PATCH /api/agent/organization-ai-decisions/:id/execute',
    scope: 'agent:organization-ai-decisions:write',
  },
];

module.exports = { AGENT_CAPABILITIES };
